### ISSUE TITLE
unbound.conf location

### ISSUE THREAD

**Issue by AirAlarm** [aleksanderbl29/docker-pihole-unbound#72]
Hello, thank you for maintaining this repo!
I have a quick question - how can I mount the container provided unbound.conf to host? 
The reason I need it, because of the machine I'm running Pihole+unbound on (PiOS). 
Here's a quick explanation: https://discourse.pi-hole.net/t/dns-leak-test-shows-google-ip-addresses-when-using-unbound/51166

It seems that because of this issue I'm seeing Google DNS servers in leak tests:
![Image](https://github.com/user-attachments/assets/e62460f6-2749-4208-bffc-e6cfcf6228f5)

To fix this issue, I need to access /etc/unbound/unbound.conf.d/resolvconf_resolvers.conf which is located somewhere in the container. OR I can set my WAN DNS to Pihole, but I've seen multiple users reporting that it is a bad idea to expose Pihole as WAN DNS.

Here's my docker-compose.yaml:

```
---
volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

services:
  pihole:
    # dns:
    #   - 127.0.0.1
    container_name: pihole-unobund
    image: aleksanderbl/pihole-unbound:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      #- 443:443/tcp #Not needed
      - 53:53/tcp
      - 53:53/udp
      - 83:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
      # - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      - TZ=${TZ:-UTC}
      - FTLCONF_webserver_api_password=${WEBPASSWORD}
      - FTLCONF_webserver_interface_theme=${WEBTHEME:-default-light}
      - FTLCONF_dns_upstreams=127.0.0.1#5335
      - FTLCONF_dns_dnssec="true"
      - FTLCONF_dns_listeningMode=single
    volumes:
      - /srv/dev-disk-***/Config/Pihole/etc-pihole/:/etc/pihole/:rw
      - /srv/dev-disk-***/Config/Pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/:rw
    restart: unless-stopped
```
